### ISSUE TITLE
Unnecessary console.log after every action

### ISSUE THREAD

**Issue by robclouth** [jhen0409/remote-redux-devtools-on-debugger#12]
Hi,
Every action leaves a "data" log in the console which clutters it up and makes it harder to debug. Is there any way to stop this?

It happens here in the debugger-ui (line 18311):

        function t(t) {
            var n = void 0;
            return t.data ? (n = t.data,
            n.id = t.id) : n = t,
            "DISCONNECTED" === n.type ? void r(t.id, void 0, !0) : (console.log("data", n),
            void e(n))
        }

**Comment by jhen0409** [comment]
Still has `data` log in latest version? I remember this to be in the older `remotedev-app` version. Try to update version & Re-run inject command.
