### ISSUE TITLE
Cannot running two instances at simultaneously running debug mode

### ISSUE THREAD

**Issue by jhen0409** [jhen0409/remote-redux-devtools-on-debugger#5]
if iOS and Android simultaneously running debug mode, the one of the connection will be lost at `Reload JS`.

Of course, `console` also have this problem, so we recommend not to simultaneously running debug mode.

**Comment by zalmoxisus** [comment]
It shouldn't be a problem starting from `remotedev-app 0.2.5` (as I see it is already here). Before we were sticked to the init action, now you may continue with new actions even when the app was refreshed. When toggling an action you will get back the lost history to know what was changed.

**Comment by jhen0409** [comment]
oh, got it. :)

It should be react-native problem itself, it crash rather than lose connection.
