### ISSUE TITLE
Support for two packager Instances? ( HMR )

### ISSUE THREAD

**Issue by duketwo** [jhen0409/remote-redux-devtools-on-debugger#9]
Hey,

As there is no real support for multiple HMR instances with one packager in react native ( https://github.com/facebook/react-native/pull/6837 ) im trying to get the redux devtools / and HMR running on both clients at the same time via two packager instances. HMR is working well with two dedicated packagers.

I know this should be rather adressed in react native, but i assume this will take a while until support for multiple HMR instances will be implemented.

react native version: 0.23
android port: 8082 ( manually set )
ios port: 8081

What ive been doing so far:

  "scripts": {
    "start": "react-native start",
    "buildRelease": "cd android && ./gradlew assembleRelease",
    "installRelease": "cd android && ./gradlew installRelease",
    "setup adb reverse 8081": "adb reverse tcp:8081 tcp:8081",
    "setup adb reverse 8082": "adb reverse tcp:8082 tcp:8082",
    "start packager 8081": "node_modules/react-native/packager/packager.sh --port=8081",
    "start packager 8082": "node_modules/react-native/packager/packager.sh --port=8082",
    "inject redux debugger 5678": "remotedev-debugger --hostname 10.0.1.112 --port 5678 --injectserver",
    "inject redux debugger 5679": "remotedev-debugger --hostname 10.0.1.112 --port 5679 --injectserver",
  }

First injecting the remotedev-debugger on port 5678, then starting packager 8081(ios), then injecting the remotedev-debugger on port 5679, then starting the second packager 8082(android)

I differentiate with Platform.OS in the configureStore to create devTools for port 5678 and 5679.

After starting chrome debugging I get a debug instance for each client. ( http://localhost:8082/debugger-ui and http://localhost:8081/debugger-ui ). The JS debugging works as expected. But I only get the android redux statetree in both redux dev windows.

Any ideas?

**Comment by jhen0409** [comment]
Thanks! We should avoid `remotedev-server` second start, because we only need one.

**Comment by duketwo** [comment]
If i leave out the other inject with port 5679, the second packager fails because its trying to use port 5678 which is already occupied.

**Comment by jhen0409** [comment]
@duketwo you're right, I'll fix it. :)

**Comment by duketwo** [comment]
Thanks. =)

**Comment by jhen0409** [comment]
Fixed via #10. Published in `v0.4.1`.
